const double DASHBOARD_IMAGE_SIZE = 72;
const double PROFILE_TAB_IMAGE_SIZE = 160.0;
const double PROFILE_SCREEN_IMAGE_SIZE = 120.0;
const double DASHBOARD_ICON_SIZE = 16;
const double CAUTION_ICON_SIZE = 64;
