const double DASHBOARD_IMAGE_SIZE = 72;
const double DASHBOARD_IMAGE_CIRCULAR_BORDER = DASHBOARD_IMAGE_SIZE/2;
const double PROFILE_IMAGE_SIZE = 160.0;
const double PROFILE_IMAGE_CIRCULAR_BORDER = PROFILE_IMAGE_SIZE/2;
const double PLANT_PROFILE_IMAGE_SIZE = 120.0;
const double PLANT_PROFILE_IMAGE_CIRCULAR_BORDER = PLANT_PROFILE_IMAGE_SIZE/2;