#The name of your workflow.
name:  Test Dart Files
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: macos-latest
    env:
      working-directory: ./instagrow 
    
    #sequence of tasks called
    steps:
     

      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      
      # Change directory from project root to flutter project
        
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.15.3'
          channel: 'dev'
            
      - run: flutter pub get
        working-directory: ${{env.working-directory}}
        
      # run static analys code
#       - run: flutter  analyze
#         working-directory: ${{env.working-directory}}
        
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
        working-directory: ${{env.working-directory}}
        
      # Upload coverage reports to Codecov
      # https://github.com/marketplace/actions/codecov
#       - run: bash codecov.sh -f instagrow/coverage/lcov.info -n  -F

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: c3666178-8858-47d5-b7f4-2eba099a5216
          file: instagrow/coverage/lcov.info
#           working-directory: ${{env.working-directory}}
